[package]
name = "fluxo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "2.0.17"
hyprland = "0.4.0-beta.3"
toml = "0.9.7"
serde = { version = "1.0.219", features = ["derive"] }
dirs = "6.0.0"
log = "0.4"
fern = "0.7"
